name: Publish DocFX Documentation

on:
  push:
    branches:
      - main  # o 'master' si tu rama principal se llama así

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Generate Documentation
      run: docfx docfx_project/docfx.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docfx_project/_site
